version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/hal-2.8"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/examples/halview"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/examples/gcode-viewer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/core/examples/position-logger"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 10
