packages:
  - packages/*
  - apps/eden/*
  - apps/examples/*

catalog:
  '@edenapp/genesis': ^0.11.1
  '@edenapp/types': ^0.11.1
  '@types/dlv': ^1.1.5
  '@types/jest': ^30.0.0
  '@types/node': ^24.13.3
  '@types/picomatch': ^4.0.2
  dlv: ^1.1.3
  dset: ^3.1.4
  jest: ^30.4.2
  node-addon-api: ^8.9.0
  node-gyp: ^13.0.1
  picomatch: ^4.0.5
  ts-jest: ^29.4.12
  tsup: ^8.5.1
  typedoc: ^0.28.20
  typescript: ^6.0.3

allowBuilds:
  '@linuxcnc-node/core': true
  '@linuxcnc-node/gcode': true
  '@linuxcnc-node/hal': true
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
