packages:
  - packages/*
  - apps/eden/*
  - apps/examples/*

catalog:
  '@edenapp/genesis': ^0.10.2
  '@edenapp/types': ^0.10.1
  
allowBuilds:
  '@linuxcnc-node/core': true
  '@linuxcnc-node/gcode': true
  '@linuxcnc-node/hal': true
  electron: true
  electron-winstaller: true
  esbuild: true
