packages:
  - packages/*
  - apps/eden/*

catalog:
  '@edenapp/babel': ^0.12.1
  '@edenapp/genesis': ^0.12.1
  '@edenapp/scripts': ^0.12.1
  '@edenapp/types': ^0.12.1
  '@types/node': ^24.13.3
  tsup: ^8.5.1
  typescript: ^6.0.3

allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
