import { NapiOptions } from "./native_type_interfaces";

// Dynamically require the native addon
// eslint-disable-next-line @typescript-eslint/no-var-requires
export const addon: NapiOptions = require("../build/Release/nml_addon.node");

// Export constants from the addon
export const Constants = {
  NMLFILE_DEFAULT: addon.NMLFILE_DEFAULT,

  TASK_MODE_MDI: addon.TASK_MODE_MDI,
  TASK_MODE_MANUAL: addon.TASK_MODE_MANUAL,
  TASK_MODE_AUTO: addon.TASK_MODE_AUTO,

  TASK_STATE_ESTOP: addon.TASK_STATE_ESTOP,
  TASK_STATE_ESTOP_RESET: addon.TASK_STATE_ESTOP_RESET,
  TASK_STATE_OFF: addon.TASK_STATE_OFF,
  TASK_STATE_ON: addon.TASK_STATE_ON,

  EXEC_STATE_ERROR: addon.EXEC_STATE_ERROR,
  EXEC_STATE_DONE: addon.EXEC_STATE_DONE,
  EXEC_STATE_WAITING_FOR_MOTION: addon.EXEC_STATE_WAITING_FOR_MOTION,
  EXEC_STATE_WAITING_FOR_MOTION_QUEUE:
    addon.EXEC_STATE_WAITING_FOR_MOTION_QUEUE,
  EXEC_STATE_WAITING_FOR_IO: addon.EXEC_STATE_WAITING_FOR_IO,
  EXEC_STATE_WAITING_FOR_MOTION_AND_IO:
    addon.EXEC_STATE_WAITING_FOR_MOTION_AND_IO,
  EXEC_STATE_WAITING_FOR_DELAY: addon.EXEC_STATE_WAITING_FOR_DELAY,
  EXEC_STATE_WAITING_FOR_SYSTEM_CMD: addon.EXEC_STATE_WAITING_FOR_SYSTEM_CMD,
  EXEC_STATE_WAITING_FOR_SPINDLE_ORIENTED:
    addon.EXEC_STATE_WAITING_FOR_SPINDLE_ORIENTED,

  INTERP_STATE_IDLE: addon.INTERP_STATE_IDLE,
  INTERP_STATE_READING: addon.INTERP_STATE_READING,
  INTERP_STATE_PAUSED: addon.INTERP_STATE_PAUSED,
  INTERP_STATE_WAITING: addon.INTERP_STATE_WAITING,

  TRAJ_MODE_FREE: addon.TRAJ_MODE_FREE,
  TRAJ_MODE_COORD: addon.TRAJ_MODE_COORD,
  TRAJ_MODE_TELEOP: addon.TRAJ_MODE_TELEOP,

  EMC_MOTION_TYPE_TRAVERSE: addon.EMC_MOTION_TYPE_TRAVERSE,
  EMC_MOTION_TYPE_FEED: addon.EMC_MOTION_TYPE_FEED,
  EMC_MOTION_TYPE_ARC: addon.EMC_MOTION_TYPE_ARC,
  EMC_MOTION_TYPE_TOOLCHANGE: addon.EMC_MOTION_TYPE_TOOLCHANGE,
  EMC_MOTION_TYPE_PROBING: addon.EMC_MOTION_TYPE_PROBING,
  EMC_MOTION_TYPE_INDEXROTARY: addon.EMC_MOTION_TYPE_INDEXROTARY,
  MOTION_TYPE_NONE: addon.MOTION_TYPE_NONE,

  KINEMATICS_IDENTITY: addon.KINEMATICS_IDENTITY,
  KINEMATICS_FORWARD_ONLY: addon.KINEMATICS_FORWARD_ONLY,
  KINEMATICS_INVERSE_ONLY: addon.KINEMATICS_INVERSE_ONLY,
  KINEMATICS_BOTH: addon.KINEMATICS_BOTH,

  RCS_STATUS_DONE: addon.RCS_STATUS_DONE,
  RCS_STATUS_ERROR: addon.RCS_STATUS_ERROR,
  RCS_STATUS_EXEC: addon.RCS_STATUS_EXEC,
  RCS_STATUS_UNINITIALIZED: addon.RCS_STATUS_UNINITIALIZED,

  SPINDLE_FORWARD: addon.SPINDLE_FORWARD,
  SPINDLE_REVERSE: addon.SPINDLE_REVERSE,
  SPINDLE_OFF: addon.SPINDLE_OFF,
  SPINDLE_INCREASE: addon.SPINDLE_INCREASE,
  SPINDLE_DECREASE: addon.SPINDLE_DECREASE,
  SPINDLE_CONSTANT: addon.SPINDLE_CONSTANT,

  MIST_ON: addon.MIST_ON,
  MIST_OFF: addon.MIST_OFF,

  FLOOD_ON: addon.FLOOD_ON,
  FLOOD_OFF: addon.FLOOD_OFF,

  BRAKE_ENGAGE: addon.BRAKE_ENGAGE,
  BRAKE_RELEASE: addon.BRAKE_RELEASE,

  JOG_STOP: addon.JOG_STOP,
  JOG_CONTINUOUS: addon.JOG_CONTINUOUS,
  JOG_INCREMENT: addon.JOG_INCREMENT,

  AUTO_RUN: addon.AUTO_RUN,
  AUTO_PAUSE: addon.AUTO_PAUSE,
  AUTO_RESUME: addon.AUTO_RESUME,
  AUTO_STEP: addon.AUTO_STEP,
  AUTO_REVERSE: addon.AUTO_REVERSE,
  AUTO_FORWARD: addon.AUTO_FORWARD,

  EMCMOT_MAX_JOINTS: addon.EMCMOT_MAX_JOINTS,
  EMCMOT_MAX_AXIS: addon.EMCMOT_MAX_AXIS,
  EMCMOT_MAX_SPINDLES: addon.EMCMOT_MAX_SPINDLES,
  EMCMOT_MAX_DIO: addon.EMCMOT_MAX_DIO,
  EMCMOT_MAX_AIO: addon.EMCMOT_MAX_AIO,
  EMCMOT_MAX_MISC_ERROR: addon.EMCMOT_MAX_MISC_ERROR,

  // NML Message Types
  EMC_OPERATOR_ERROR_TYPE: addon.EMC_OPERATOR_ERROR_TYPE,
  EMC_OPERATOR_TEXT_TYPE: addon.EMC_OPERATOR_TEXT_TYPE,
  EMC_OPERATOR_DISPLAY_TYPE: addon.EMC_OPERATOR_DISPLAY_TYPE,
  NML_ERROR_TYPE: addon.NML_ERROR_TYPE,
  NML_TEXT_TYPE: addon.NML_TEXT_TYPE,
  NML_DISPLAY_TYPE: addon.NML_DISPLAY_TYPE,

  JOINT_TYPE_LINEAR: addon.JOINT_TYPE_LINEAR,
  JOINT_TYPE_ANGULAR: addon.JOINT_TYPE_ANGULAR,
};
